### ISSUE TITLE
Issues with playerquit and mysql statement

### ISSUE THREAD

**Issue by IlPicasso** [j0ach1mmall3/UltimateCosmetics#29] opened 2015-12-12 13:58 UTC
http://hastebin.com/capogekoda.sm

It happens a lot my Log is filled with that

**Comment by j0ach1mmall3** [comment] 2015-12-12 14:01
I'll see what I can do about it

**Comment by j0ach1mmall3** [comment] 2015-12-12 14:09
Duplicate of #27

**Closed by j0ach1mmall3** 2015-12-12 14:09 UTC
Labels: duplicate
