### ISSUE TITLE
Aura kick players bungeecoord

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#154] opened 2016-04-30 15:14 UTC
Hi, when Aura was enabled on 1.9.2 server on my prison server, every players that try to connect are kick and be teleport to the lobby...

I use latest ultimatecosmetics version 4.1.1...

I don't know if its normal or no, but this is very bad...

**Comment by maxlehot1234** [comment] 2016-04-30 15:18
@j0ach1mmall3 
Directly when I enable aura, I can't reload the plugin (check #153 )
So I think this is anothger problem with your plugin.

**Comment by maxlehot1234** [comment] 2016-05-01 19:25
@j0ach1mmall3 Any idea why this happen?

**Comment by maxlehot1234** [comment] 2016-05-02 01:42
@j0ach1mmall3 ?? Please answer me, I really need a fix for this. Thank you

**Comment by j0ach1mmall3** [comment] 2016-05-02 05:45
It's difficult to fix without an error

**Comment by maxlehot1234** [comment] 2016-05-02 19:04
I know, but I receive nothing, execept the fact that I am disconnect directly after I login to the server with a message: the server has been down (message from bungeecoord) but the server was never down, I can simply reconnect to it...

This is really bad, because I need auras on my server XD

**Comment by j0ach1mmall3** [comment] 2016-05-03 05:48
Well, I'll try to look into it

**Comment by maxlehot1234** [comment] 2016-05-03 06:35
Ok thank you, because it is very bad :(

**Comment by j0ach1mmall3** [comment] 2016-05-04 13:10
Pretty sure this is a duplicate of #120

**Closed by j0ach1mmall3** 2016-05-04 13:10 UTC
