### ISSUE TITLE
Reload command error occured...

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#157] opened 2016-05-05 02:12 UTC
Hi, I just downlaod and installed latest ultimatecosmetics version and I get this message in the console when I try to reload the plugin after enabling auras...
http://pastebin.com/9nMhe78h

Any fix for this when you can?
I need to reload the plugin with Plugman for the moment....

Auras works great, execpt the reload command after enabling them
I try to enable gadgets, auras, morphs, pets and reload the plugin, I get the same error ^^^^^ and this can happen with maybe all other cosmetics things...

If you can fix them, it could be really nice ;)

Thank you so much

**Comment by j0ach1mmall3** [comment] 2016-05-05 05:35
Please don't use plugman

**Comment by maxlehot1234** [comment] 2016-05-05 09:38
I AM FORCE to use it because the reload command simply doesn't work...
And NO ISSUE using plugman...

**Comment by j0ach1mmall3** [comment] 2016-05-05 10:22
The issue is not an issue with my plugin, it's an issue with java. I have no idea to fix it

**Comment by maxlehot1234** [comment] 2016-05-06 01:22
It is so badd... :( :(

**Comment by j0ach1mmall3** [comment] 2016-05-08 07:15
Will be fixed in the latest update

**Closed by j0ach1mmall3** 2016-05-08 07:15 UTC
