### ISSUE TITLE
pet issue

### ISSUE THREAD

**Issue by zythium** [j0ach1mmall3/UltimateCosmetics#185] opened 2016-08-15 09:59 UTC
chicken still lay eggs as pets, this can be a problem when eggs are used as a premium item or are used as an special item in other plugins, an option to stop this would be usefull,

hitting baby rabbit or chicken pets with eggs causes them to grow in adults until re summoned,

snowman still lays down snow layers that dont de-spawn causing issues in non player mineable areas

is it possible to have pets like the wither not constantly attack you? (more of an annoyance than a bug)

**Comment by j0ach1mmall3** [comment] 2016-08-20 20:37
> chicken still lay eggs as pets, this can be a problem when eggs are used as a premium item or are used as an special item in other plugins, an option to stop this would be usefull,
Should be fixed in a new update
> hitting baby rabbit or chicken pets with eggs causes them to grow in adults until re summoned,
> snowman still lays down snow layers that dont de-spawn causing issues in non player mineable areas
Can't reproduce any of those
> is it possible to have pets like the wither not constantly attack you? (more of an annoyance than a bug)
No, sorry

**Closed by j0ach1mmall3** 2016-08-20 20:37 UTC
Labels: bug

**Comment by zythium** [comment] 2016-08-21 06:35
egg thing only happens when someone else hits it with eggs, sorry should of mentioned that,
