### ISSUE TITLE
Cannot load plugins/UltimateCosmetics/data.yml

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#175] opened 2016-06-11 19:15 UTC
Hi, I continue to get this problem: http://pastebin.com/EUhhr6BX

I try to remve the data.yml file and restart the server and I continue to get this problem...

So until you found a solution or a fix for this, I need to remove the remove from my 2 servers, because it simply SPAM my servers console and this is very bad.

Please do not tell that my file was fuck, because I can't edit it, so the plugin make it fuck, not me...

Thanks again

**Comment by j0ach1mmall3** [comment] 2016-06-12 06:40
You can use sqlite

**Comment by maxlehot1234** [comment] 2016-06-13 10:06
I already use sqlite... This is the problem...

**Comment by j0ach1mmall3** [comment] 2016-06-13 12:51
Well if you use SQLite, then the plugin won't mess with data.yml?

**Comment by j0ach1mmall3** [comment] 2016-06-28 09:25
Duplicate of #174

**Closed by j0ach1mmall3** 2016-06-28 09:25 UTC
