### ISSUE TITLE
ERROR Spam my Console. Please fix it!

### ISSUE THREAD

**Issue by RobinArnhardt** [j0ach1mmall3/UltimateCosmetics#76] opened 2016-01-15 03:04 UTC
Hello,

this error: http://prntscr.com/9q9mtm

Spam my console. Please fix it!

Thanks.

**Comment by j0ach1mmall3** [comment] 2016-01-16 09:31
Duplicate of #70

**Comment by j0ach1mmall3** [comment] 2016-01-16 09:32
Sorry, my bad, this isn't a duplicate

**Comment by j0ach1mmall3** [comment] 2016-01-18 15:40
Is this fixed?

**Comment by RobinArnhardt** [comment] 2016-01-19 00:22
I think, but I'm not sure!

**Closed** 2016-01-21 09:13 UTC
Labels: bug
