### ISSUE TITLE
Plugin error (doesnt want to work :P )

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#151] opened 2016-04-28 22:11 UTC
Hi, I update JLIB to latest version and ultimatecosmetics too, but now, cosmetics plugin doesn't work anymore:
When I try to reload the plugin:
http://pastebin.com/jheCkGJv

When the server start:
http://pastebin.com/zPT3iy08

Please fix this problem as soon as possible

**Comment by j0ach1mmall3** [comment] 2016-04-29 05:41
I am looking into it

**Comment by j0ach1mmall3** [comment] 2016-04-29 14:30
Duplicate of #150

**Closed by j0ach1mmall3** 2016-04-29 14:30 UTC
