### ISSUE TITLE
Plugin Not loading 

### ISSUE THREAD

**Issue by MCLimited** [j0ach1mmall3/UltimateCosmetics#152] opened 2016-04-30 01:22 UTC
I uses the newest version of UltimateCosmetics and Jlib. This is the error log.

[19:04:47] [Server thread/ERROR]: Error occurred while enabling UltimateCosmetics v4.1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/j0ach1mmall3/jlib/plugin/JlibPlugin
	at com.j0ach1mmall3.ultimatecosmetics.modules.auras.AurasModule.onEnable(AurasModule.java:21) ~[?:?]
	at com.j0ach1mmall3.jlib.plugin.modularization.PluginModule.setEnabled(PluginModule.java:47) ~[?:?]
	at com.j0ach1mmall3.ultimatecosmetics.Main.loadModules(Main.java:415) ~[?:?]
	at com.j0ach1mmall3.ultimatecosmetics.Main.onEnable(Main.java:180) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot_latest.jar:git-Spigot-e6f93f4-7a6b143]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot_latest.jar:git-Spigot-e6f93f4-7a6b143]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot_latest.jar:git-Spigot-e6f93f4-7a6b143]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot_latest.jar:git-Spigot-e6f93f4-7a6b143]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot_latest.jar:git-Spigot-e6f93f4-7a6b143]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot_latest.jar:git-Spigot-e6f93f4-7a6b143]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot_latest.jar:git-Spigot-e6f93f4-7a6b143]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot_latest.jar:git-Spigot-e6f93f4-7a6b143]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot_latest.jar:git-Spigot-e6f93f4-7a6b143]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot_latest.jar:git-Spigot-e6f93f4-7a6b143]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.ClassNotFoundException: com.j0ach1mmall3.jlib.plugin.JlibPlugin
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_77]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot_latest.jar:git-Spigot-e6f93f4-7a6b143]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot_latest.jar:git-Spigot-e6f93f4-7a6b143]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
	... 15 more

**Comment by j0ach1mmall3** [comment] 2016-04-30 05:03
Duplicate of #150

**Closed by j0ach1mmall3** 2016-04-30 05:03 UTC
