### ISSUE TITLE
BroadcastSound deprecation warning

### ISSUE THREAD

**Issue by Thebowers89** [j0ach1mmall3/UltimateCosmetics#74] opened 2016-01-11 17:00 UTC
Several deprecation warnings:
[15:14:34] [Server thread/INFO]: [JLib] [0;33;22mWARNING: I'm using deprecated method com.j0ach1mmall3.jlib.methods.General.broadcastSound(General.java:96) at com.j0ach1mmall3.ultimatecosmetics.internal.gadgets.GadgetsListener.onInteract(GadgetsListener.java:405)! [m
 -Kerlab

**Comment by j0ach1mmall3** [comment] 2016-01-16 09:31
Duplicate of #70

**Closed by j0ach1mmall3** 2016-01-16 09:31 UTC
